### ISSUE TITLE
Vehicle Information "Model" includes a leading forward slash "/"

### ISSUE THREAD

**Issue by JAudi23** [hudsonbrendon/HA-drivvo#63]
The following code in my yaml for vehicle information "Model" includes a leading forward slash "/" before the model name.
I've confirmed that the entry in the Drivvo app is correct and does not include this character.

This is occurring on all 3 vehicles that I have set up.

![Image](https://github.com/user-attachments/assets/a91fb14a-9334-4163-9f89-1f0d1ad5d9d4)

```yml type: entities
title: Vehicle Information
entities:
  - entity: sensor.2003_audi_a4_vehicle
```
